### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by snoop2head** [jonghwanhyeon/python-mecab-ko#15]
안녕하세요,

좋은 라이브러리를 만들어주셔서 감사합니다.
다만 제가 사용하는 와중에 에러가 발생해서 문의드립니다.

### Encountered Error
```python
import mecab
mecab = mecab.MeCab()
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/ipykernel_31265/2337645710.py in <module>
      1 import mecab
----> 2 mecab = mecab.MeCab()

~/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab/mecab.py in __init__(self, dicpath)
     51             argument = '-d %s' % dicpath
     52 
---> 53         self.tagger = _mecab.Tagger(argument)
     54 
     55     def parse(self, sentence):

TypeError: pybind11::init(): factory function returned nullptr
```

### Environment
- OS: macOS Catalina version 10.15.7
- Virtual Environment: pyenv, python 3.8.3, pip 21.2.4

### Suspected Reason
가상환경에 `pip install -v python-mecab-ko` 명령어를 입력했고 설치 메세지를 하단에 첨부하였습니다.
`ERROR: Failed building wheel for python-mecab-ko` 부분이 해당 에러와 연관이 있을까요?

```
Collecting python-mecab-ko
  Downloading python-mecab-ko-1.0.12.tar.gz (9.7 kB)
    Running command python setup.py egg_info
    running egg_info
    creating /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info
    writing /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/dependency_links.txt
    writing requirements to /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/requires.txt
    writing top-level names to /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/top_level.txt
    writing manifest file '/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/SOURCES.txt'
    reading manifest file '/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/SOURCES.txt'
    writing manifest file '/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-pip-egg-info-x1pa9x7e/python_mecab_ko.egg-info/SOURCES.txt'
Collecting pybind11~=2.0
  Downloading pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
     |████████████████████████████████| 208 kB 10.8 MB/s 
Building wheels for collected packages: python-mecab-ko
  Running command /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"'; __file__='"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-wheel-qd42g16i
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.8
  creating build/lib.macosx-10.15-x86_64-3.8/mecab
  copying mecab/mecab.py -> build/lib.macosx-10.15-x86_64-3.8/mecab
  copying mecab/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/mecab
  running build_ext
  creating var
  creating var/folders
  creating var/folders/f8
  creating var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn
  creating var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c /var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmpw5_bo5mq.cpp -o var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmpw5_bo5mq.o -std=c++14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c /var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmpqpy_i80_.cpp -o var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmpqpy_i80_.o -fvisibility=hidden
  building '_mecab' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py", line 127, in <module>
      setup(
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py", line 43, in build_extensions
      super().build_extensions()
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/ccompiler.py", line 565, in compile
      self._setup_compile(output_dir, macros, include_dirs, sources,
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/ccompiler.py", line 341, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/Users/noopy/.pyenv/versions/3.8.3/lib/python3.8/distutils/ccompiler.py", line 1076, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
    File "/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py", line 95, in __str__
      return func(*self.args, **self.kwargs)
    File "/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py", line 108, in get_pybind_include
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  Building wheel for python-mecab-ko (setup.py) ... error
  ERROR: Failed building wheel for python-mecab-ko
  Running setup.py clean for python-mecab-ko
  Running command /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"'; __file__='"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/lib.macosx-10.15-x86_64-3.8' (and everything under it)
  'build/bdist.macosx-10.15-x86_64' does not exist -- can't clean it
  'build/scripts-3.8' does not exist -- can't clean it
  removing 'build'
Failed to build python-mecab-ko
Installing collected packages: pybind11, python-mecab-ko
  changing mode of /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/bin/pybind11-config to 755
    Running command /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"'; __file__='"'"'/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-install-ebh7m4yr/python-mecab-ko_c9a1e70c8f7a40478847d2da0decfe64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-record-a4g5xbwc/install-record.txt --single-version-externally-managed --compile --install-headers /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include/site/python3.8/python-mecab-ko
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.8
    creating build/lib.macosx-10.15-x86_64-3.8/mecab
    copying mecab/mecab.py -> build/lib.macosx-10.15-x86_64-3.8/mecab
    copying mecab/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/mecab
    running build_ext
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c /var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmp_9tfjp0a.cpp -o var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmp_9tfjp0a.o -std=c++14
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c /var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmp6csgssk3.cpp -o var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/tmp6csgssk3.o -fvisibility=hidden
    building '_mecab' extension
    creating build/temp.macosx-10.15-x86_64-3.8
    creating build/temp.macosx-10.15-x86_64-3.8/mecab
    creating build/temp.macosx-10.15-x86_64-3.8/mecab/pybind
    creating build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/node.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/node.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/path.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/path.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/lattice.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/lattice.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/dictionaryinfo.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/dictionaryinfo.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/tagger.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/tagger.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/pybind11/include -I/usr/local/include -I/Users/noopy/.pyenv/versions/3.8.3/envs/aitech/include -I/Users/noopy/.pyenv/versions/3.8.3/include/python3.8 -c mecab/pybind/_mecab/_mecab.cpp -o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/_mecab.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0.12" -std=c++14 -fvisibility=hidden
    clang++ -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/noopy/.pyenv/versions/3.8.3/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/noopy/.pyenv/versions/3.8.3/lib build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/node.o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/path.o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/lattice.o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/dictionaryinfo.o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/tagger.o build/temp.macosx-10.15-x86_64-3.8/mecab/pybind/_mecab/_mecab.o -L/usr/local/lib -L/usr/local/lib -lmecab -o build/lib.macosx-10.15-x86_64-3.8/_mecab.cpython-38-darwin.so
    running install_lib
    copying build/lib.macosx-10.15-x86_64-3.8/_mecab.cpython-38-darwin.so -> /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages
    creating /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab
    copying build/lib.macosx-10.15-x86_64-3.8/mecab/mecab.py -> /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab
    copying build/lib.macosx-10.15-x86_64-3.8/mecab/__init__.py -> /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab
    byte-compiling /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab/mecab.py to mecab.cpython-38.pyc
    byte-compiling /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/mecab/__init__.py to __init__.cpython-38.pyc
    running install_data
    creating /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/scripts
    copying scripts/install-mecab-ko.py -> /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/scripts
    running install_egg_info
    running egg_info
    writing python_mecab_ko.egg-info/PKG-INFO
    writing dependency_links to python_mecab_ko.egg-info/dependency_links.txt
    writing requirements to python_mecab_ko.egg-info/requires.txt
    writing top-level names to python_mecab_ko.egg-info/top_level.txt
    reading manifest file 'python_mecab_ko.egg-info/SOURCES.txt'
    writing manifest file 'python_mecab_ko.egg-info/SOURCES.txt'
    Copying python_mecab_ko.egg-info to /Users/noopy/.pyenv/versions/3.8.3/envs/aitech/lib/python3.8/site-packages/python_mecab_ko-1.0.12-py3.8.egg-info
    running install_scripts
    writing list of installed files to '/private/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/pip-record-a4g5xbwc/install-record.txt'
    Running setup.py install for python-mecab-ko ... done
  DEPRECATION: python-mecab-ko was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

Successfully installed pybind11-2.8.1 python-mecab-ko-1.0.12
```

**Comment by upskyy** [comment]
저도 동일한 에러였는데, `bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)` 실행해서 해결했습니다!
