### ISSUE TITLE
Error on import mecab on macOS

### ISSUE THREAD

**Issue by BLKSerene** [jonghwanhyeon/python-mecab-ko#19]
Hi, I use OS X 10.11 with Python 3.10.11 and everything works fine for `python-mecab-ko` 1.3.3. But after upgrading to `python-mecab-ko` 1.3.5, an error occurs on `import mecab`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mecab/__init__.py", line 1, in <module>
    from .mecab import MeCab, MeCabError, mecabrc_path
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mecab/mecab.py", line 8, in <module>
    import _mecab
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_mecab.cpython-310-darwin.so, 2): Library not loaded: @loader_path/mecab/.dylibs/libmecab.2.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_mecab.cpython-310-darwin.so
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mecab/.dylibs/libmecab.2.dylib: cannot load 'libmecab.2.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mecab/.dylibs/libmecab.2.dylib: cannot load 'libmecab.2.dylib' (load command 0x80000034 is unknown)
```

There are also some issues when running tests on CI ([Github Actions](https://github.com/BLKSerene/Wordless/actions/runs/9136231662/job/25124740125) and [Azure Pipelines](https://dev.azure.com/blkserene/BLKSerene%20-%20Github/_build/results?buildId=1601&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0)) with macOS 11:
```
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tests_nlp/tests_spacy/test_spacy_eng.py:19: in <module>
    from tests.tests_nlp.tests_spacy import test_spacy
tests/tests_nlp/tests_spacy/test_spacy.py:19: in <module>
    from tests import wl_test_init, wl_test_lang_examples
tests/wl_test_init.py:[29](https://github.com/BLKSerene/Wordless/actions/runs/9136231662/job/25124740125#step:5:30): in <module>
    from tests import wl_test_file_area
tests/wl_test_file_area.py:28: in <module>
    from wordless import wl_file_area
wordless/wl_file_area.py:38: in <module>
    from wordless.wl_checks import wl_checks_files, wl_checks_misc
wordless/wl_checks/wl_checks_files.py:24: in <module>
    from wordless.wl_checks import wl_checks_work_area
wordless/wl_checks/wl_checks_work_area.py:25: in <module>
    from wordless.wl_dialogs import wl_dialogs_errs, wl_msg_boxes
wordless/wl_dialogs/wl_dialogs_errs.py:23: in <module>
    from wordless.wl_widgets import wl_labels, wl_tables
wordless/wl_widgets/wl_tables.py:37: in <module>
    from wordless.wl_nlp import wl_nlp_utils
wordless/wl_nlp/wl_nlp_utils.py:[31](https://github.com/BLKSerene/Wordless/actions/runs/9136231662/job/25124740125#step:5:32): in <module>
    import mecab
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/mecab/__init__.py:1: in <module>
    from .mecab import MeCab, MeCabError, mecabrc_path
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/mecab/mecab.py:8: in <module>
    import _mecab
E   ImportError: dlopen(/Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_mecab.cpython-310-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
E     Referenced from: /Users/runner/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/mecab/.dylibs/libmecab.2.dylib (which was built for Mac OS X 13.0)
E     Expected in: /usr/lib/libc++.1.dylib
```

It works with Xcode 14.1 on [CI](https://app.circleci.com/pipelines/github/BLKSerene/Wordless/1222/workflows/2b0cfb59-0f34-4d1d-85db-f4890f5b8565/jobs/1395).

**Comment by jonghwanhyeon** [comment]
Sorry for the late response 😢. Does this problem still occur? If it does, can you describe in detail how to reproduce it? I have checked that the wheels work on macOS 14 with both Intel and Apple silicon chips, at least.

**Comment by BLKSerene** [comment]
It seems that the wheel of the new version (1.3.5) works only on macOS >=12 (or 13?), but does not work on older macOSes such as 10.11. Version 1.3.3 does not have this problem.

To reproduce this issue, just `pip install python-mecab-ko` on an old macOS and do a simple import:
```
import mecab
```

**Comment by BLKSerene** [comment]
@jonghwanhyeon With version 1.3.6, a simple import now works on OS X 10.11. But a segfault occurs when following the example in the README:
Again, this works for version 1.3.3.
```
>>> from mecab import MeCab
>>> mecab = MeCab()
>>> mecab.morphs('영등포구청역에 있는 맛집 좀 알려주세요.')
Segmentation fault: 11
```

```
Process:               Python [637]
Path:                  /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.11.9 (3.11.9)
Code Type:             X86-64 (Native)
Parent Process:        bash [463]
Responsible:           Terminal [460]
User ID:               501

Date/Time:             2024-07-14 19:54:27.493 +0800
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        D1A03976-B238-A2F2-411D-7A6C04F7D178


Time Awake Since Boot: 690 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libc++abi.dylib               	0x00007fff8305d6e0 __cxxabiv1::scan_eh_tab(__cxxabiv1::(anonymous namespace)::scan_results&, _Unwind_Action, bool, _Unwind_Exception*, _Unwind_Context*) + 809
1   libc++abi.dylib               	0x00007fff8305d31e __gxx_personality_v0 + 178
2   libunwind.dylib               	0x00007fff96a209ba _Unwind_RaiseException + 162
3   libc++abi.dylib               	0x00007fff8305ca59 __cxa_throw + 104
4   _mecab.cpython-311-darwin.so  	0x000000010d1e8316 std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> pybind11::detail::argument_loader<pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&>::call_impl<std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&>, pybind11::iterator pybind11::detail::make_iterator_impl<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>(Iterator, Iterator)::'lambda0'(pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&)&, 0ul, pybind11::detail::void_type>(pybind11::iterator pybind11::detail::make_iterator_impl<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>(Iterator, Iterator)::'lambda0'(pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&)&&&, std::__1::integer_sequence<unsigned long, 0ul>, Iterator&&) + 182
5   _mecab.cpython-311-darwin.so  	0x000000010d1e821b void pybind11::cpp_function::initialize<pybind11::iterator pybind11::detail::make_iterator_impl<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>(Iterator, Iterator)::'lambda0'(pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&), std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const, pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::return_value_policy>(pybind11::iterator pybind11::detail::make_iterator_impl<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>(Iterator, Iterator)::'lambda0'(pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&)&&, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const (*)(pybind11::detail::iterator_state<pybind11::detail::iterator_access<Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>, (pybind11::return_value_policy)6, Iterator, Iterator, std::__1::tuple<std::__1::tuple<unsigned long, unsigned long> const, mecab_node_t const&> const>&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::return_value_policy const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 123
6   _mecab.cpython-311-darwin.so  	0x000000010d1d0491 pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 4881
7   org.python.python             	0x000000010c39d7b4 cfunction_call + 52
8   org.python.python             	0x000000010c338061 _PyObject_MakeTpCall + 129
9   org.python.python             	0x000000010c33c634 method_vectorcall + 756
10  org.python.python             	0x000000010c3cef9a vectorcall_method + 122
11  org.python.python             	0x000000010c3c683f slot_tp_iternext + 47
12  org.python.python             	0x000000010c4694ad _PyEval_EvalFrameDefault + 53917
13  org.python.python             	0x000000010c45aeca PyEval_EvalCode + 282
14  org.python.python             	0x000000010c4e6a27 PyRun_InteractiveOneObjectEx + 839
15  org.python.python             	0x000000010c4e58b6 _PyRun_InteractiveLoopObject + 118
16  org.python.python             	0x000000010c4e515f _PyRun_AnyFileObject + 63
17  org.python.python             	0x000000010c4e9ebd PyRun_AnyFileExFlags + 125
18  org.python.python             	0x000000010c50df2e pymain_run_stdin + 142
19  org.python.python             	0x000000010c50d4cd Py_RunMain + 1645
20  org.python.python             	0x000000010c50e6cb pymain_main + 43
21  org.python.python             	0x000000010c50f1ea Py_BytesMain + 42
22  libdyld.dylib                 	0x00007fff826965ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010d1c5000  rbx: 0x00007fd7f059b5e8  rcx: 0x01000007feedfacf  rdx: 0x00007fff539777e8
  rdi: 0x000000010d1c5000  rsi: 0x000000010d1c5000  rbp: 0x00007fff53977830  rsp: 0x00007fff53977790
   r8: 0x00007fd7f059b5e8   r9: 0x000000000000009b  r10: 0x0000000000001310  r11: 0x00000000510558d1
  r12: 0x0000000000000001  r13: 0x000000010d20064b  r14: 0x0000000000000003  r15: 0x0000000000000001
  rip: 0x00007fff8305d6e0  rfl: 0x0000000000010206  cr2: 0x000000010d2002ec
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     13


Binary Images:
       0x10c287000 -        0x10c28aff3 +org.python.python (3.11.9 - 3.11.9) <99386555-1891-3414-9160-653FAC551834> /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python
       0x10c29d000 -        0x10c680ff7 +org.python.python (3.11.9, [c] 2001-2023 Python Software Foundation. - 3.11.9) <84181E25-B58A-3F52-8124-46B12C49ED45> /Library/Frameworks/Python.framework/Versions/3.11/Python
       0x10ceab000 -        0x10ceaeff7 +readline.cpython-311-darwin.so (0) <32F1D580-7B5D-3CEE-A443-3D5212D85AAD> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/readline.cpython-311-darwin.so
       0x10cebf000 -        0x10cf0effb +libncursesw.5.dylib (0) <A1C049AB-04A1-3FEA-AB52-50ADA928306D> /Library/Frameworks/Python.framework/Versions/3.11/lib/libncursesw.5.dylib
       0x10d04a000 -        0x10d04dff7 +_opcode.cpython-311-darwin.so (0) <17DA58AB-C0A0-3B32-A40F-EAEAE30DFEBF> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_opcode.cpython-311-darwin.so
       0x10d1b5000 -        0x10d1b8ff3 +_typing.cpython-311-darwin.so (0) <22D6F273-D0D3-3480-BFB4-0B0643592435> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_typing.cpython-311-darwin.so
       0x10d1c5000 -        0x10d210ff3 +_mecab.cpython-311-darwin.so (???) <DDEB464F-1BAA-3415-A9CB-B5BBE89B5BAA> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_mecab.cpython-311-darwin.so
       0x10d251000 -        0x10d2b4ff7 +libmecab.2.dylib (3) <8F10ADF1-8784-3F06-8FF9-40D826206F19> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mecab/.dylibs/libmecab.2.dylib
    0x7fff6a1ad000 -     0x7fff6a1e4a47  dyld (360.22) <6B9CD3BA-2D60-3629-A0CB-AB810F55E8DD> /usr/lib/dyld
    0x7fff82693000 -     0x7fff82696ffb  libdyld.dylib (360.22) <E0CE4C3B-38DF-37FB-A74E-866938E1AF92> /usr/lib/system/libdyld.dylib
    0x7fff82cf3000 -     0x7fff82d0aff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff82d0b000 -     0x7fff82d0bff7  liblaunch.dylib (765.70.2) <4B800A8C-6C75-3279-92E0-FBA668812B55> /usr/lib/system/liblaunch.dylib
    0x7fff83039000 -     0x7fff83063ff7  libc++abi.dylib (307.4) <D24E06BF-6522-3C4A-BD0C-11C42BA4D8E8> /usr/lib/libc++abi.dylib
    0x7fff83257000 -     0x7fff83258fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff832e2000 -     0x7fff834effff  libicucore.A.dylib (551.51.6) <142B2AD5-0A50-3382-8213-096E925863F7> /usr/lib/libicucore.A.dylib
    0x7fff85274000 -     0x7fff85275ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff852fe000 -     0x7fff85302fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff85dae000 -     0x7fff85db6fff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff863dc000 -     0x7fff863deff7  libsystem_configuration.dylib (802.40.13) <B815C622-96EF-388A-823B-B02618E7F190> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8886b000 -     0x7fff88889ffb  libedit.3.dylib (43) <1D3E3152-4001-3C19-B56A-7543F1BBA47C> /usr/lib/libedit.3.dylib
    0x7fff889c8000 -     0x7fff889e4ff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff89f6b000 -     0x7fff89f7cff7  libsystem_trace.dylib (201.10.3) <0ED15BED-B1F8-3845-9EC1-CC0B54B6BF1B> /usr/lib/system/libsystem_trace.dylib
    0x7fff8a8e5000 -     0x7fff8a8e6ffb  libSystem.B.dylib (1226.10.1) <9A358336-F9EE-301B-A00D-D91C591BA684> /usr/lib/libSystem.B.dylib
    0x7fff8a8e7000 -     0x7fff8a8e8fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8b173000 -     0x7fff8b5e9fff  com.apple.CoreFoundation (6.9 - 1259.22) <53EFA4A7-4614-383E-BEEE-B8B9D9D19FFA> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8be2c000 -     0x7fff8be72ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff8c1d0000 -     0x7fff8c532f3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff8d11a000 -     0x7fff8d125ff7  libcommonCrypto.dylib (60075.50.1) <E48A81E7-56B0-37F5-9611-E896B8E16B4D> /usr/lib/system/libcommonCrypto.dylib
    0x7fff8d17d000 -     0x7fff8d1a6fff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fff8d4e0000 -     0x7fff8d533ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff8df75000 -     0x7fff8df7dffb  libsystem_dnssd.dylib (625.60.5) <8BE2BAFE-B2A3-38FA-A960-F6884217F54D> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff8edb2000 -     0x7fff8edb4fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff8f391000 -     0x7fff8f399fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff8f472000 -     0x7fff8f47bff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff90777000 -     0x7fff907a8ff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff90ad9000 -     0x7fff90b02ff7  libxpc.dylib (765.70.2) <7978B4D9-7970-3302-87FA-75709127DBD2> /usr/lib/system/libxpc.dylib
    0x7fff914cf000 -     0x7fff914cfff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff91a38000 -     0x7fff91a3dff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff91cda000 -     0x7fff91d51feb  libcorecrypto.dylib (335.50.2) <4E339108-3997-39D3-BB58-C5A0340E3651> /usr/lib/system/libcorecrypto.dylib
    0x7fff94564000 -     0x7fff9456bff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff94e95000 -     0x7fff94f22fef  libsystem_c.dylib (1082.60.1) <0F0C7ED5-3902-3427-9C1D-E2F130B528C5> /usr/lib/system/libsystem_c.dylib
    0x7fff95b3f000 -     0x7fff95b48ff7  libsystem_pthread.dylib (138.10.4) <62FC23B9-1DEE-3918-A30D-A58EC95A0720> /usr/lib/system/libsystem_pthread.dylib
    0x7fff95b4a000 -     0x7fff95b77fff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff95fa1000 -     0x7fff95fa4fff  libsystem_sandbox.dylib (460.60.4) <71D697CA-7339-37C7-8DAF-3BAA1D57B56A> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff96903000 -     0x7fff96932fc3  libsystem_m.dylib (3105) <8A645D53-92DD-3C2E-8AFA-F28BC63E3657> /usr/lib/system/libsystem_m.dylib
    0x7fff96a20000 -     0x7fff96a25ff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff96ff0000 -     0x7fff97007ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff9763f000 -     0x7fff97731ff7  libiconv.2.dylib (44) <F05A0A5A-92A9-3668-8F20-F27CBDA26BE9> /usr/lib/libiconv.2.dylib
    0x7fff97f19000 -     0x7fff97f21fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff9835c000 -     0x7fff9836dff7  libz.1.dylib (61.20.1) <B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib
    0x7fff9838a000 -     0x7fff983f0ff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib
    0x7fff98450000 -     0x7fff98450ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff984fd000 -     0x7fff984ffff7  libquarantine.dylib (80) <5B351BEC-27CC-3935-82F3-A065CC764255> /usr/lib/system/libquarantine.dylib
    0x7fff987ec000 -     0x7fff9880aff7  libsystem_kernel.dylib (3248.73.11) <4810EB90-DEEB-3E89-9ACA-BECC351E72F0> /usr/lib/system/libsystem_kernel.dylib
    0x7fff98a70000 -     0x7fff98a71fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 287
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=114.0M resident=0K(0%) swapped_out_or_unallocated=114.0M(100%)
Writable regions: Total=41.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=41.9M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            19.0M       13 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            384K        2         reserved VM address space (unallocated)
STACK GUARD                          4K        2 
Stack                             16.0M        2 
VM_ALLOCATE                       4116K        7 
__DATA                            4628K       56 
__LINKEDIT                        93.7M       17 
__TEXT                            20.3M       56 
__UNICODE                          552K        2 
mapped file                       96.7M        5 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            257.3M      160 
TOTAL, minus reserved VM space   256.9M      160 

Model: VMware20,1, BootROM VMW201.00V.21805430.B64.2305221830, 2 processors, 2.48 GHz, 2 GB, SMC 1.16f8
Graphics: Display, PCI, 128 MB
Memory Module: RAM slot #0/RAM slot #0, 2 GB, DRAM, 0 MHz, VMware Virtual RAM, VMW-2048MB
Bluetooth: Version 4.4.6f4, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: VMware Virtual SATA Hard Drive, 64.42 GB
Serial ATA Device: VMware Virtual SATA CDRW Drive
USB Device: USB Bus
USB Device: VMware Virtual USB Hub
USB Device: Virtual Bluetooth Adapter
USB Device: VMware Virtual USB Keyboard
USB Device: VMware Virtual USB Mouse
USB Device: USB 2.0 Bus
Thunderbolt Bus: 
```

**Comment by jonghwanhyeon** [comment]
I am trying to solve this problem! The x86-64 wheel file is built to support Mac OS X 10.9 and later versions on macOS 13, which seems to be causing the issue.

**Comment by jonghwanhyeon** [comment]
The version currently being built is expected to work on Mac OS X 10.9 or higher. Please check once the build is complete. 🙏

**Comment by BLKSerene** [comment]
Many thanks to your efforts. I confirm that with version 1.3.7, the issue has gone away on OS X 10.11 and everything works like a charm now.
